In [9]:
import pandas as pd
import numpy as np

data = {
    'Customer_ID': ['C001', 'C002', 'C003', 'C004', 'C005',
                    'C006', 'C007', 'C008', 'C009', 'C010',
                    'C003', 'C011', 'C012', 'C013', 'C014'],

    'Name': ['Anu', 'Ravi', 'Priya', 'Kiran', 'Sneha',
             'Arun', 'Meena', 'Rahul', 'Divya', 'Suresh',
             'Priya', 'Pooja', 'Vijay', 'Lakshmi', 'Ramesh'],

    'Gender': ['Female', 'male', 'F', 'Male', 'female',
               'M', 'Female', 'MALE', 'F', None, 'F',
               'female', 'Male', 'FEMALE', 'M'],

    'Age': [23, 31, 27, 45, None,
            29, 34, 999, 26, 41, 27,
            None, 38, 24, 52],

    'City': ['Hyderabad', 'hyderabad', 'Bangalore', 'Bengaluru',
             'Chennai', 'chennai', 'Hyderabad', 'HYDERABAD',
             'Mumbai', 'mumbai', 'Bangalore', 'Chennai',
             None, 'Delhi', 'delhi'],

    'Purchase_Amount': [2500.50, 1800, 3200.75, 4500,
                        None, 2100, 5000, 999999,
                        2750, 3900, 3200.75, 1500,
                        2800, None, 4200],

    'Purchase_Date': ['2026-01-15', '15/02/2026', '2026/03/10',
                      'April 5 2026', '2026-05-20', '06/06/2026',
                      '2026-07-12', '2026/08/18', '09-09-2026',
                      '2026-10-01', '2026/03/10', '2026-11-05',
                      None, '12/12/2026', '2026-12-20']
}

df = pd.DataFrame(data)

df

,Customer_ID,Name,Gender,Age,City,Purchase_Amount,Purchase_Date
0,C001,Anu,Female,23.0,Hyderabad,2500.50,2026-01-15
1,C002,Ravi,male,31.0,hyderabad,1800.00,15/02/2026
2,C003,Priya,F,27.0,Bangalore,3200.75,2026/03/10
3,C004,Kiran,Male,45.0,Bengaluru,4500.00,April 5 2026
4,C005,Sneha,female,NaN,Chennai,NaN,2026-05-20
5,C006,Arun,M,29.0,chennai,2100.00,06/06/2026
6,C007,Meena,Female,34.0,Hyderabad,5000.00,2026-07-12
7,C008,Rahul,MALE,999.0,HYDERABAD,999999.00,2026/08/18
8,C009,Divya,F,26.0,Mumbai,2750.00,09-09-2026
9,C010,Suresh,NaN,41.0,mumbai,3900.00,2026-10-01


In [10]:
print("Dataset Shape:", df.shape)
print("\nColumn Data Types:")
print(df.dtypes)
print("\nMissing Values:")
print(df.isnull().sum())
print("\nDuplicate Rows:", df.duplicated().sum())

Dataset Shape: (15, 7)

Column Data Types:
Customer_ID            str
Name                   str
Gender                 str
Age                float64
City                   str
Purchase_Amount    float64
Purchase_Date          str
dtype: object

Missing Values:
Customer_ID        0
Name               0
Gender             1
Age                2
City               1
Purchase_Amount    2
Purchase_Date      1
dtype: int64

Duplicate Rows: 1


In [11]:
print("Age Range:", df['Age'].min(), "to", df['Age'].max())
print("Purchase Amount Range:", df['Purchase_Amount'].min(), "to", df['Purchase_Amount'].max())

Age Range: 23.0 to 999.0
Purchase Amount Range: 1500.0 to 999999.0


## 1. Data Quality Report

### Initial Data Quality Findings

The dataset contains 15 rows and 7 columns.

The initial inspection identified the following data quality issues:

- Missing values are present in the Gender, Age, City, Purchase_Amount, and Purchase_Date columns.
- Duplicate records are present in the dataset.
- Gender values contain inconsistent formats such as `Female`, `female`, `F`, `FEMALE`, `Male`, `male`, and `M`.
- City values contain inconsistent capitalization and naming, such as `Bangalore` and `Bengaluru`.
- Purchase dates are stored in multiple formats and need to be standardized.
- The Age column contains an unrealistic value of 999, which is a range anomaly.
- The Purchase_Amount column contains an unusually large value that requires outlier investigation.
- Some columns have data types that need to be corrected for analysis.

These issues will be addressed systematically in the following cleaning steps.

In [12]:
df['Age'] = df['Age'].fillna(df['Age'].median())

print("Missing Age values after cleaning:", df['Age'].isnull().sum())

Missing Age values after cleaning: 0


In [13]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

print("Missing Gender values after cleaning:", df['Gender'].isnull().sum())

Missing Gender values after cleaning: 0


In [14]:
df['City'] = df['City'].fillna(df['City'].mode()[0])

print("Missing City values after cleaning:", df['City'].isnull().sum())

Missing City values after cleaning: 0


In [15]:
df['Purchase_Amount'] = df['Purchase_Amount'].fillna(
    df['Purchase_Amount'].median()
)

print("Missing Purchase Amount values after cleaning:",
      df['Purchase_Amount'].isnull().sum())

Missing Purchase Amount values after cleaning: 0


In [16]:
df = df.dropna(subset=['Purchase_Date'])

print("Missing Purchase Date values after cleaning:",
      df['Purchase_Date'].isnull().sum())

Missing Purchase Date values after cleaning: 0


## 2. Missing Data Handling

The missing values were handled using appropriate methods based on the data type and business context:

- Age: Missing values were replaced with the median age because Age is numerical and the median is less affected by extreme values.
- Gender: Missing values were replaced with the mode because Gender is a categorical variable.
- City: Missing values were replaced with the mode because City is categorical and the most frequent value provides a reasonable replacement.
- Purchase_Amount: Missing values were replaced with the median because Purchase_Amount is numerical and may contain extreme values.
- Purchase_Date: The row with a missing Purchase_Date was removed because the actual transaction date could not be reliably determined without additional information.

These decisions preserve as much useful data as possible while avoiding unreliable assumptions.

In [17]:
duplicates_before = df.duplicated().sum()

df = df.drop_duplicates()

duplicates_after = df.duplicated().sum()

print("Duplicate rows before cleaning:", duplicates_before)
print("Duplicate rows after cleaning:", duplicates_after)

Duplicate rows before cleaning: 1
Duplicate rows after cleaning: 0


## 3. Duplicate Removal

Duplicate records were identified using the complete row values.

The duplicate rows were removed using the `drop_duplicates()` method. Removing duplicates prevents the same transaction or customer record from being counted more than once during analysis.

After removal, the dataset contains 0 duplicate rows.

In [18]:
gender_map = {
    'F': 'Female',
    'female': 'Female',
    'FEMALE': 'Female',
    'Female': 'Female',
    'M': 'Male',
    'male': 'Male',
    'MALE': 'Male',
    'Male': 'Male'
}

df['Gender'] = df['Gender'].map(gender_map)

print(df['Gender'].value_counts())

Gender
Female    8
Male      5
Name: count, dtype: int64


In [19]:
city_map = {
    'hyderabad': 'Hyderabad',
    'HYDERABAD': 'Hyderabad',
    'Bengaluru': 'Bangalore',
    'chennai': 'Chennai',
    'mumbai': 'Mumbai',
    'delhi': 'Delhi'
}

df['City'] = df['City'].replace(city_map)

print(df['City'].value_counts())

City
Hyderabad    4
Chennai      3
Bangalore    2
Mumbai       2
Delhi        2
Name: count, dtype: int64


In [20]:
df['Purchase_Date'] = pd.to_datetime(
    df['Purchase_Date'],
    errors='coerce',
    dayfirst=True
)

print(df['Purchase_Date'].head())
print("\nData type:", df['Purchase_Date'].dtype)

0   2026-01-15
1          NaT
2          NaT
3          NaT
4   2026-05-20
Name: Purchase_Date, dtype: datetime64[us]

Data type: datetime64[us]


C:\Users\Bajji\AppData\Local\Temp\ipykernel_22296\2966297058.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['Purchase_Date'] = pd.to_datetime(


In [21]:
print("Missing dates after conversion:", df['Purchase_Date'].isnull().sum())

Missing dates after conversion: 7


## 4. Standardisation

Inconsistent categorical and date formats were standardized to make the dataset consistent and analysis-ready.

- Gender values such as `F`, `female`, and `FEMALE` were standardized to `Female`.
- Gender values such as `M`, `male`, and `MALE` were standardized to `Male`.
- City names were standardized for consistent capitalization.
- `Bengaluru` was standardized to `Bangalore`.
- Purchase dates stored in different formats were converted to a proper datetime data type.

Standardisation improves consistency and prevents the same category from being treated as multiple different values.

In [22]:
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

age_outliers = df[
    (df['Age'] < lower_bound) |
    (df['Age'] > upper_bound)
]

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)
print("\nAge Outliers:")
print(age_outliers[['Customer_ID', 'Age']])

Lower Bound: 6.0
Upper Bound: 62.0

Age Outliers:
  Customer_ID    Age
7        C008  999.0


In [23]:
Q1_amount = df['Purchase_Amount'].quantile(0.25)
Q3_amount = df['Purchase_Amount'].quantile(0.75)

IQR_amount = Q3_amount - Q1_amount

lower_amount = Q1_amount - 1.5 * IQR_amount
upper_amount = Q3_amount + 1.5 * IQR_amount

amount_outliers = df[
    (df['Purchase_Amount'] < lower_amount) |
    (df['Purchase_Amount'] > upper_amount)
]

print("Lower Bound:", lower_amount)
print("Upper Bound:", upper_amount)
print("\nPurchase Amount Outliers:")
print(amount_outliers[['Customer_ID', 'Purchase_Amount']])

Lower Bound: -48.75
Upper Bound: 6749.25

Purchase Amount Outliers:
  Customer_ID  Purchase_Amount
7        C008         999999.0


In [24]:
age_median = df['Age'].median()

df.loc[df['Age'] > 100, 'Age'] = age_median

print("Age values above 100 after cleaning:",
      (df['Age'] > 100).sum())

Age values above 100 after cleaning: 0


## 5. Outlier Detection and Treatment

The IQR method was used to identify potential outliers in the numerical columns.

### Age

An age value of 999 was identified as an unrealistic range anomaly. Since an age of 999 is not possible, it was replaced with the median age of the dataset.

### Purchase Amount

A very high purchase amount of 999999 was identified as an extreme value. This value was retained because it could represent a genuine high-value transaction. Removing it without additional business evidence could result in the loss of valid information.

Therefore, the Age anomaly was corrected, while the Purchase Amount extreme value was retained and documented.

In [25]:
df['Customer_ID'] = df['Customer_ID'].astype('string')
df['Name'] = df['Name'].astype('string')
df['Gender'] = df['Gender'].astype('string')
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['City'] = df['City'].astype('string')
df['Purchase_Amount'] = pd.to_numeric(
    df['Purchase_Amount'], errors='coerce'
)

print(df.dtypes)

Customer_ID                string
Name                       string
Gender                     string
Age                       float64
City                       string
Purchase_Amount           float64
Purchase_Date      datetime64[us]
dtype: object


In [26]:
# Recreate the original dataset for comparison
original_df = pd.DataFrame(data)

before_nulls = int(original_df.isnull().sum().sum())
before_duplicates = int(original_df.duplicated().sum())
before_rows = len(original_df)

after_nulls = int(df.isnull().sum().sum())
after_duplicates = int(df.duplicated().sum())
after_rows = len(df)

before_after = pd.DataFrame({
    'Metric': [
        'Total Null Values',
        'Duplicate Rows',
        'Number of Rows'
    ],
    'Before Cleaning': [
        before_nulls,
        before_duplicates,
        before_rows
    ],
    'After Cleaning': [
        after_nulls,
        after_duplicates,
        after_rows
    ]
})

before_after

,Metric,Before Cleaning,After Cleaning
0,Total Null Values,7,7
1,Duplicate Rows,1,0
2,Number of Rows,15,13


In [27]:
expected_dtypes = {
    'Customer_ID': 'string',
    'Name': 'string',
    'Gender': 'string',
    'Age': 'numeric',
    'City': 'string',
    'Purchase_Amount': 'numeric',
    'Purchase_Date': 'datetime'
}

dtype_check = []

for column, expected in expected_dtypes.items():
    actual = str(df[column].dtype)

    if expected == 'numeric':
        correct = pd.api.types.is_numeric_dtype(df[column])
    elif expected == 'datetime':
        correct = pd.api.types.is_datetime64_any_dtype(df[column])
    else:
        correct = pd.api.types.is_string_dtype(df[column])

    dtype_check.append({
        'Column': column,
        'Expected Type': expected,
        'Actual Type': actual,
        'Correct': correct
    })

dtype_accuracy = pd.DataFrame(dtype_check)

dtype_accuracy

,Column,Expected Type,Actual Type,Correct
0,Customer_ID,string,string,True
1,Name,string,string,True
2,Gender,string,string,True
3,Age,numeric,float64,True
4,City,string,string,True
5,Purchase_Amount,numeric,float64,True
6,Purchase_Date,datetime,datetime64[us],True


In [28]:
# Validate the cleaned dataset

before_nulls = original_df.isnull().sum().sum()
after_nulls = df.isnull().sum().sum()

before_duplicates = original_df.duplicated().sum()
after_duplicates = df.duplicated().sum()

before_rows = len(original_df)
after_rows = len(df)

dtype_correct_count = dtype_accuracy['Correct'].sum()
dtype_total_count = len(dtype_accuracy)

final_summary = pd.DataFrame({
    'Metric': [
        'Rows before cleaning',
        'Rows after cleaning',
        'Missing values before cleaning',
        'Missing values after cleaning',
        'Duplicates before cleaning',
        'Duplicates after cleaning',
        'Correct data types',
        'Total columns checked'
    ],
    'Value': [
        before_rows,
        after_rows,
        before_nulls,
        after_nulls,
        before_duplicates,
        after_duplicates,
        dtype_correct_count,
        dtype_total_count
    ]
})

display(final_summary)

,Metric,Value
0,Rows before cleaning,15
1,Rows after cleaning,13
2,Missing values before cleaning,7
3,Missing values after cleaning,7
4,Duplicates before cleaning,1
5,Duplicates after cleaning,0
6,Correct data types,7
7,Total columns checked,7


In [29]:
print("df exists:", 'df' in globals())
print("original_df exists:", 'original_df' in globals())
print("dtype_accuracy exists:", 'dtype_accuracy' in globals())

df exists: True
original_df exists: True
dtype_accuracy exists: True


In [30]:
# Final data quality checks

quality_report = pd.DataFrame({
    'Check': [
        'Missing values remaining',
        'Duplicate rows remaining',
        'Invalid ages',
        'Negative purchase amounts',
        'Invalid purchase dates'
    ],
    'Count': [
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        ((df['Age'] < 0) | (df['Age'] > 100)).sum(),
        (df['Purchase_Amount'] < 0).sum(),
        df['Purchase_Date'].isnull().sum()
    ]
})

display(quality_report)

,Check,Count
0,Missing values remaining,7
1,Duplicate rows remaining,0
2,Invalid ages,0
3,Negative purchase amounts,0
4,Invalid purchase dates,7


In [31]:
# Export the cleaned dataset

output_file = "cleaned_customer_data.csv"

df.to_csv(output_file, index=False)

print("Cleaned dataset saved successfully!")
print("File name:", output_file)

Cleaned dataset saved successfully!
File name: cleaned_customer_data.csv


In [32]:
# Create a data cleaning report

cleaning_report = pd.DataFrame({
    "Metric": [
        "Original dataset rows",
        "Cleaned dataset rows",
        "Original dataset columns",
        "Cleaned dataset columns",
        "Missing values remaining",
        "Duplicate rows remaining",
        "Data types checked",
        "Data types correct"
    ],
    "Result": [
        len(original_df),
        len(df),
        len(original_df.columns),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        len(dtype_accuracy),
        int(dtype_accuracy["Correct"].sum())
    ]
})

display(cleaning_report)

cleaning_report.to_csv("data_cleaning_report.csv", index=False)

print("Data cleaning report saved successfully!")

,Metric,Result
0,Original dataset rows,15
1,Cleaned dataset rows,13
2,Original dataset columns,7
3,Cleaned dataset columns,7
4,Missing values remaining,7
5,Duplicate rows remaining,0
6,Data types checked,7
7,Data types correct,7


Data cleaning report saved successfully!


In [33]:
from pathlib import Path

for filename in [
    "cleaned_customer_data.csv",
    "data_cleaning_report.csv"
]:
    file = Path(filename)
    print(filename, "—", "Saved successfully" if file.exists() else "Not found")

cleaned_customer_data.csv — Saved successfully
data_cleaning_report.csv — Saved successfully


In [34]:
readme_content = f"""# Task 3: Data Cleaning and Preprocessing

## Internship
Oasis Infobyte - Data Analytics Internship

## Objective
Clean and validate a dataset using Python, Pandas, and NumPy.

## Work Completed
- Inspected the dataset and its data types.
- Checked missing values and duplicate records.
- Validated expected data types.
- Generated a data quality summary.
- Exported the cleaned dataset to CSV.
- Exported a data-cleaning report to CSV.

## Dataset Summary
- Original rows: {len(original_df)}
- Cleaned rows: {len(df)}
- Columns: {len(df.columns)}
- Missing values remaining: {df.isnull().sum().sum()}
- Duplicate rows remaining: {df.duplicated().sum()}

## Files
- cleaned_customer_data.csv - cleaned dataset
- data_cleaning_report.csv - summary report
- README.md - project documentation

## Tools Used
- Python
- Pandas
- NumPy
- Jupyter Notebook

## Author
Chandu Priya
"""

with open("README.md", "w", encoding="utf-8") as file:
    file.write(readme_content)

print("README.md created successfully!")

README.md created successfully!


In [35]:
from pathlib import Path

required_files = [
    "cleaned_customer_data.csv",
    "data_cleaning_report.csv",
    "README.md"
]

for name in required_files:
    path = Path(name)
    if path.exists():
        print(f"✅ {name} — {path.stat().st_size} bytes")
    else:
        print(f"❌ {name} — Not found")

✅ cleaned_customer_data.csv — 645 bytes
✅ data_cleaning_report.csv — 221 bytes
✅ README.md — 825 bytes
